const express = require('express');
const jwt = require('jsonwebtoken');
const { ROLES } = require('../../utils/constants');
const { setJSON, getJSON, del } = require('../../services/redisService');
const roomService = require('../../services/roomService');

const TOKEN_TTL = parseInt(process.env.ROOM_TTL_SECONDS || '14400', 10);

const router = express.Router();
const SECRET = process.env.JWT_SECRET;
const EXPIRES = process.env.JWT_EXPIRES_IN || '6h';

// POC only — no credentials check
router.post('/trainer-token', (req, res) => {
  const { trainerId = `trainer-${Date.now()}`, name = 'Trainer' } = req.body;
  const token = jwt.sign({ sub: trainerId, name, role: ROLES.TRAINER }, SECRET, { expiresIn: EXPIRES });
  res.json({ token });
});

// POC only — no credentials check
router.post('/learner-token', (req, res) => {
  const { learnerId = `learner-${Date.now()}`, name = 'Learner' } = req.body;
  const token = jwt.sign({ sub: learnerId, name, role: ROLES.LEARNER }, SECRET, { expiresIn: EXPIRES });
  res.json({ token });
});

// Display token — public, no auth required — resolves room code → signed JWT role=display
router.get('/display-token', async (req, res) => {
  const { room } = req.query;
  if (!room) return res.status(400).json({ error: 'room required' });
  const roomData = await roomService.getRoomByCode(room);
  if (!roomData) return res.status(404).json({ error: 'Room not found' });
  const token = jwt.sign({ sub: 'display', role: ROLES.DISPLAY, roomId: roomData.id }, SECRET, { expiresIn: EXPIRES });
  res.json({ token, roomId: roomData.id, code: room });
});

// Store token → LMS identity mapping (generated by SCORM, consumed by smartphone)
router.post('/register-token', async (req, res) => {
  const { token, studentId, studentName, roomCode } = req.body;
  if (!token || !studentId || !roomCode) {
    return res.status(400).json({ error: 'token, studentId and roomCode required' });
  }
  await setJSON(`token:${token}`, { studentId, studentName: studentName || studentId, roomCode }, TOKEN_TTL);
  res.json({ ok: true });
});

// Resolve token → LMS identity (called by smartphone after scanning QR)
router.get('/resolve-token', async (req, res) => {
  const { token } = req.query;
  if (!token) return res.status(400).json({ error: 'token required' });
  const data = await getJSON(`token:${token}`);
  if (!data) return res.status(404).json({ error: 'Token expired or not found' });
  res.json(data);
});

module.exports = router;
